---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Talia Olsen"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

There are seven airports represented, but some values are missing airport names. Atlanta Airport has 23 samples that are missing years. The dataset appears to go from 2005 to 2015.

```{python}
sample_size = (
  df
  .group_by("airport_code", "year")
  .len(name = "sample_size")
  .sort("airport_code", "year", descending = True)
)
sample_size
```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

I chose proportion delayed, as it acurately represents an airport regardless of number of total flights, or number of delay hours if it has a lot less or a lot more planes than another airport. An airport with fewer planes will be underrepresented in any other metric, and an airport with more planes will be overrepresented. Proportion seemed the most fair metric to use.



```{python}
worst_delay = (
    df
    .group_by("airport_code")
    .agg(
      pl
      .col("num_of_flights_total")
      .sum()
      .alias("total_flights"),
      pl.col("num_of_delays_total")
      .sum()
      .alias("total_delayed_flights"),
      pl.col("minutes_delayed_total")
      .mean()
      .alias("avg_delay_time_minutes")
    )
    .with_columns(
      (pl.col("total_delayed_flights") / pl.col("total_flights"))
      .alias("proportion_delayed"),
      (pl.col("avg_delay_time_minutes") / 60)
      .alias("avg_delay_hours")
    )
    .select(
      "airport_code",
      "total_flights",
      "total_delayed_flights",
      "proportion_delayed",
      "avg_delay_hours"
    )
    .sort("proportion_delayed", descending = True)
)

worst_delay
```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

According to this chart, the San Francisco Airport has the worst delays at 26.1% of all flights being delayed, and the Salt Lake City Airport has the best delays at only 14.6% of flights being delayed. Your best chance of an on time flight is at SLC, and if you're flying through SFO, you have just over a 1 in 4 chance of your flight being delayed.


```{python}
Flight_delay_plot = (
  ggplot(data = worst_delay.sort("proportion_delayed", descending = True), mapping = aes(x = "airport_code", y = "proportion_delayed", color = "airport_code", fill = "airport_code"))
  +geom_bar(stat = "identity")
  +labs(
    title = "Proportion of Delayed Flights by Airport",
    x = "Airport Code",
    y  = "Proportion of Delayed Flights"
  )
  +scale_y_continuous(limits=[0, 0.30], format = ".1%")
  +theme(legend_position = 'none')
)

Flight_delay_plot
```