---
title: "Client Report - Flights: Creating New Columns"
subtitle: "Unit 2 Task 1"
author: "Talia Olsen"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *
import polars.selectors as cs

LetsPlot.setup_html(isolated_frame=True)
```



```{python}
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## QUESTION 1

1. __Create a new 'season' column.__ Define 'season' as:
    1. Winter for January, Febuary (note the mispelling), March
    1. Spring for April, May, June
    1. Summer for  July, August, September
    1. Fall for October, November, December
    1. All other rows can be assigned a value of 'Unknown' 

_No discussion needed for this question_
(However I think its silly how the months are supposed to be divided)

```{python}
# Conditionally divide each month into a season.
seasons = df.with_columns(
  pl.when(pl.col("month").is_in(["January", "Febuary", "March"])).then(pl.lit("Winter"))
  .when(pl.col("month").is_in(["April", "May", "June"])).then(pl.lit("Spring"))
  .when(pl.col("month").is_in(["July", "August", "September"])).then(pl.lit("Summer"))
  .when(pl.col("month").is_in(["October", "November", "December"])).then(pl.lit("Fall"))
  .otherwise(pl.lit("Unknown"))
  .alias("season")
)

seasons.head()
```

## QUESTION 2

1. __Divide all the columns by 1000 whose name starts with num_of.__ Be sure to first filter out rows that contain problematic values for the columns like -999 or 1500+.

_No discussion needed for this question_


```{python}
seasons_clean =(
# Select the columns that need values replaced and replace with appropriate values
    seasons.with_columns(
      pl.col("num_of_delays_carrier")
      .replace("1500+", 1500)
      .cast(pl.Int64)
    )
    .with_columns(
      pl.col("num_of_delays_late_aircraft")
      .replace(-999, None)
      .fill_null(pl.col("num_of_delays_late_aircraft").mean())
    )
    # Divide selected columns by 1000
    .with_columns(cs.matches('^num_of')/1000)
)

seasons_clean.head()
```

## QUESTION 3

1. According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “nas” and “late_aircraft” categories. __Using the columns you modified in the bullet above, your job is to create a new column that calculates the total number of flights (in 1,000's) delayed by weather (both severe and mild).__ Show your work by printing the first 5 rows of the dataset. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the "late_aircraft" category are due to weather  
    a. From April through August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%  

_No discussion needed for this question_

```{python}
weather_delays = (
  seasons_clean.with_columns(
    # Creates a new column with the conditionally divided values, to leave the original column unchanged
    num_of_delays_nas_percent = pl.when(pl.col("month").is_in(["April", "May", "June", "July", "August"])).then(pl.col("num_of_delays_nas") * 0.4)
    .otherwise(pl.col("num_of_delays_nas") * 0.65),
    # Creates a new column with the divided values, to leave the original column unchanged
    num_of_delays_late_aircraft_percent = pl.col("num_of_delays_late_aircraft") * 0.3,
    # Creates a new column with the total of the three columns
    total_weather_delays = pl.sum_horizontal(
      pl.col(["num_of_delays_weather", "num_of_delays_nas", "num_of_delays_late_aircraft"])
    )
  )
  # Drops the calculation columns so that the dataset isn't cluttered
  .drop(["num_of_delays_nas_percent", "num_of_delays_late_aircraft_percent"])
)

weather_delays.head()
```

## QUESTION 4

1. __Using the new weather variable calculated above, create a boxplot showing the distribution of flights delayed by weather for each season. Describe what you learn from this graph.__    

Looking at the chart, Winter, Spring, and Summer have very similar distributions, with the max values being in the high 7,000s, a median around 2,000, and a lower quartile of around 1,000. They also have the highest number of delays overall. Fall has a lower distribution, with a max of around 6,850, a median of 1.8k, and a lower quartile of about 0.8k. The unknown category contains a fair chunk of data, and has a much lower median than any of the other options.

From this, it seems like the end of the year (October, November, and December) has fewer weather delays than the other months of the year, although overall it is pretty close. The unknown category is likely skewing the data as it includes a lot of missing data, comparable to the sets that include 3 months.

```{python}
weather_plot = (
  ggplot(data = weather_delays, mapping = aes( x = "season", y = "total_weather_delays", color = "season"))
  +geom_boxplot()
  +scale_y_continuous(format = ".2f")
  +labs(title = "Distribution of Flights Delayed by Weather by Season", x = "Season", y = "Total Weather Delays (by 1000's)")
)

weather_plot
```