---
title: "Client Report - Famous Names"
subtitle: "Unit 1 Task 3"
author: "Talia Olsen"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import io
import requests
import urllib3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
url = "https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv"

response = requests.get(url, verify=False)
response.raise_for_status()

df = pl.read_csv(io.BytesIO(response.content))
```



## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__Make a new column that represents the total number of babies with your name for only those states in which you have lived. (If you have only ever lived in one state, pick at least one other state so you get practice summing across columns). Make a graph displaying that total for your name over time.__

The name Talia increased starting around 1995, and continued to increase until 2007, after which it dropped a little and then plateaued around 23 uses a year. My birth year, 2006 was right around a rise in popularity. (It is worth noting as well that I did not live in either of these states for any significant amount of time, or around my birth year, as I am Canadian)

No AI used

```{python}
# Q1
talia = df.filter(
  (pl.col("name") == "Talia")
)

talia_babies = talia.with_columns(
  pl.sum_horizontal(
    pl.col(["ID", "UT"]).fill_null(0)
  )
  .alias("Total_Talias")
)

t_babies_plot = (
  ggplot(
    data = talia_babies, 
    mapping = aes(x = "year", y = "Total_Talias"))
    +geom_vline(xintercept = 2006, color = "Purple", linetype = 3)
    # Text to label line
    +geom_text(x = 2007, y = 10, label = "My Birth Year", color = "purple", size = 5, hjust = 0, angle = 270)
    +geom_line()
    +scale_x_continuous(format = 'd')
    +labs(
      title = "Use of the Name Talia in Utah and Idaho Over Time"
    )
    +theme_classic()
)
t_babies_plot
```


## QUESTION 2

1. __Let's look at a name that is special for members of the church: Brigham. For each year, calculate what proportion of babies named Brigham were born in Idaho and Utah? Make a graph displaying the proportion over time.__  

The name Brigham made up nearly 100% of the names use from the start of this dataset in 1970 to 1996. 

The red rectangle indicates the space in 1992 that reads 0%, which can indicate that the name usage in those states was less than 5 babies, in which case for privacy policies of the SSA it is rounded to 0. 

Since 1996, Brigham has been on the decline in popularity with small spikes in use every few years.

Googled what the potential reason for the drop in name use in 1992 could be, and consequently consulted google AI

```{python}
# Q2
brigham = df.filter(
  (pl.col("name") == "Brigham")
)

brigham_babies = brigham.with_columns(
  pl.sum_horizontal(
    pl.col(["ID", "UT"]).fill_null(0)
  )
  .alias("Total_Brighams")
)

brigham_prop = brigham_babies.with_columns(
  pl.when(pl.col("Total") > 0)
  .then(pl.col("Total_Brighams")/pl.col("Total"))
  .otherwise(None)
  .alias("ID_UT_prop")
)

t_babies_plot = (
  ggplot(
    data = brigham_prop, 
    mapping = aes(x = "year", y = "ID_UT_prop"))
    +geom_rect(xmin = 1987, xmax = 1993, ymin = 0, ymax = 1, fill = "#dba5a5")
    +geom_line()
    +scale_x_continuous(format = 'd')
    +scale_y_continuous(format = ".1%")
    +labs(
      title = "Proportional Use of the Name Brigham in Utah and Idaho Over Time"
    )
    +theme_classic()
)
t_babies_plot

```

<!-- Make sure at least one of your charts includes reference marks!! -->

## QUESTION 3

1. __Consider doing some data validation. For the name David, calculate a sum of all 50 states and District of Columbia for each year. Now compare that total to the value in the 'Total' column. In which years, if any, do they not agree?__

There are no years that mismatch the calculated total and the recorded total.

No AI use

```{python}
# Q3
state_cols = [
    "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
    "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME",
    "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM",
    "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX",
    "UT", "VA", "VT", "WA", "WI", "WV", "WY"
]
data_val = (
    df
    .filter(pl.col("name") == "David")
    .with_columns(
        pl.sum_horizontal(pl.col(state_cols))
          .alias("Calculated_Total")
    )
    .with_columns(
        (pl.col("Calculated_Total") != pl.col("Total"))
           .alias("Does_Not_Match")
    )
    .select(["year", "Calculated_Total", "Total", "Does_Not_Match"])
    .sort("year")
)

data_val.filter(pl.col("Does_Not_Match")).head()
```